DROP TABLE IF EXISTS COLORS;

CREATE TABLE COLORS(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
);

INSERT INTO COLORS (ID, NAME)
VALUES (1, "RED");

INSERT INTO COLORS (ID, NAME)
VALUES (2, 'BLUE');

INSERT INTO COLORS (ID, NAME)
VALUES (2, 'YELLOW');
